channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.9.2
  - pip=20.1
  - robotframework=4.0.1
  - robotframework-seleniumlibrary=5.1.3
